backend-grails-pari/grails-app/domain/backend/grails/pari/CaisseSite.groovy
package backend.grails.pari

import grails.gorm.async.AsyncEntity

import java.sql.Date

//class CaisseSite implements AsyncEntity<CaisseSite> {
class CaisseSite{
    double amount
    Date dateIns
    static constraints = {
        amount blank: false, nullable: false
        dateIns blank: false, nullable: false
    }
    static mapping = {
        version false
    }
}

backend-grails-pari/grails-app/domain/backend/grails/pari/Paris.groovy
package backend.grails.pari

import grails.gorm.async.AsyncEntity

import java.sql.Date

//class Paris implements AsyncEntity<Paris> {
class Paris{
    Date datePari
    double totalAmount
    boolean isPayed
    long idUser

    static hasMany = [pariMise: ParisDetail]
    static constraints = {
        datePari blank: false, nullable: false
    }

    static mapping = {
        version false
    }
}

backend-grails-pari/grails-app/controllers/backend/grails/pari/ApiBasicController.groovy
package backend.grails.pari

import grails.converters.JSON
import grails.converters.XML

class ApiBasicController {

    def serializeData(object, format)
    {
        switch (format)
        {
            case 'json':
            case 'application/json':
            case 'text/json':
                render object as JSON
                break
            case 'xml':
            case 'application/xml':
            case 'text/xml':
                render object as XML
                break
            default:
                render object as JSON
                break
        }
    }
}

backend-grails-pari/grails-app/controllers/backend/grails/pari/ApiCaisseController.groovy
package backend.grails.pari

import grails.converters.JSON
import grails.converters.XML

import javax.servlet.http.HttpServletResponse
import java.sql.Date

class ApiCaisseController extends ApiBasicController{

    CaisseSiteService caisseSiteService

    def caisse(){
        try {
            switch (request.getMethod()) {
                case "GET":
                    def caisse = caisseSiteService.list()
                    serializeData(caisse, request.getHeader("Accept"))
                    break
                case "POST":
                    CaisseSite caisse = new CaisseSite()
                    String amount = params.amount
                    caisse.amount = amount.toDouble()
                    String dateIns = params.dateins
                    caisse.dateIns = Date.valueOf(dateIns)
                    if(!caisse.validate()){
                        throw new Exception('Une erreur de validation est survenue')
                    }
                    def caisseInstance = caisseSiteService.save(caisse)
                    response.status = HttpServletResponse.SC_CREATED;
                    serializeData(caisseInstance, request.getHeader("Accept"))
                    break
                default:
                    return response.status = HttpServletResponse.SC_METHOD_NOT_ALLOWED
                    break
            }
        }catch(Exception ex){
            response.status = HttpServletResponse.SC_INTERNAL_SERVER_ERROR
            return  serializeData([message : ex.getMessage()], request.getHeader("Accept"))
        }
    }
}

backend-grails-pari/grails-app/controllers/backend/grails/pari/ApiMatchController.groovy
package backend.grails.pari

import javax.servlet.http.HttpServletResponse

class ApiMatchController extends ApiBasicController{

    MatchCustomService matchCustomService
    def matchPlusParie() {
        try {
            switch (request.getMethod()) {
                case "GET":
                    def most = []
                    def jsonObject = request.JSON
                    def max = jsonObject.max ? jsonObject.max.toLong(): 3
                    def offset = jsonObject.offset ? jsonObject.offset.toLong() : 1
                    def result = matchCustomService.matchMostBet(max, offset).each {
                        item ->
                            most.add([count: item[0], idmatch: item[1]])
                    }
                    serializeData(most, request.getHeader("Accept"))
                    break
                default:
                    return response.status = HttpServletResponse.SC_METHOD_NOT_ALLOWED
                    break
            }
        }catch(Exception ex){
            response.status = HttpServletResponse.SC_INTERNAL_SERVER_ERROR
            return  serializeData([message : ex.getMessage()], request.getHeader("Accept"))
        }
    }


}

backend-grails-pari/grails-app/controllers/backend/grails/pari/ApiPariController.groovy
package backend.grails.pari

import backend.grails.marshaller.Marshaller
import grails.converters.JSON
import grails.converters.XML

import javax.servlet.http.HttpServletResponse
import java.sql.Date

class ApiPariController extends ApiBasicController {

    ParisService parisService
    PariCustomService pariCustomService
    ParisDetailService parisDetailService
    MvntAfterMatchService mvntAfterMatchService

    def paris() {
        try {
            switch (request.getMethod()) {
                case "GET":
                    def paris = parisService.list()
                    serializeData(paris, request.getHeader("Accept"))
                    break
                case "POST":
                    def jsonObject = request.JSON
                    def parimise = pariCustomService.insertPari(jsonObject)
                    response.status = HttpServletResponse.SC_CREATED;
                    serializeData(parimise, request.getHeader("Accept"))
                    break
                default:
                    return response.status = HttpServletResponse.SC_METHOD_NOT_ALLOWED
                    break
            }
        }
        catch(Exception ex){
            response.status = HttpServletResponse.SC_INTERNAL_SERVER_ERROR
            return  serializeData([message : ex.getMessage()], request.getHeader("Accept"))
        }
    }

    def pari(){
        try{
            if(!params.id)
                return response.status = HttpServletResponse.SC_BAD_REQUEST
            def pari = parisService.get(params.id)
            if(!pari)
                return response.status = HttpServletResponse.SC_NOT_FOUND
            switch (request.getMethod()) {
                case "PATCH":
                    def jsonObject = request.JSON
                    if (jsonObject.totalamount)
                        pari.totalAmount = Double.valueOf(jsonObject.totalamount)
                    if (jsonObject.ispayed)
                        pari.isPayed = Boolean.valueOf(jsonObject.ispayed)
                    if (!pari.validate()) {
                        throw new Exception('Une erreur de validation est survenue')
                    }
                    parisService.save(pari)
                    response.status = HttpServletResponse.SC_OK
                    serializeData([message : "L'annonce "+params.id+" a été modifiée"], request.getHeader("Accept"))
                    break
                default:
                    return response.status = HttpServletResponse.SC_METHOD_NOT_ALLOWED
                    break
            }
        }
        catch(Exception ex){
            response.status = HttpServletResponse.SC_INTERNAL_SERVER_ERROR
            return  serializeData([message : ex.getMessage()], request.getHeader("Accept"))
        }
    }

    def paricustom(){
        try {
            switch (request.getMethod()) {
                case "GET":
                    def paris = pariCustomService.getNotPayed(params.id)
                    Marshaller.pariFormat();
                    serializeData(paris, request.getHeader("Accept"))
                    break
                default:
                    return response.status = HttpServletResponse.SC_METHOD_NOT_ALLOWED
                    break
            }
        }catch(Exception ex){
            response.status = HttpServletResponse.SC_INTERNAL_SERVER_ERROR
            return  serializeData([message : ex.getMessage()], request.getHeader("Accept"))
        }
    }

    def pariwithdetails(){
        try {
            switch (request.getMethod()) {
                case "GET":
                    long iduser = params.iduser.toLong()
                    def count = pariCustomService.getBetInProgressByIdUser(iduser)
                    serializeData([count: count.toLong()], request.getHeader("Accept"))
                    break
                case "POST":
                    def jsonObject = request.JSON
                    def parimise = pariCustomService.insertdetails(jsonObject)
                    response.status = HttpServletResponse.SC_CREATED;
                    serializeData(parimise, request.getHeader("Accept"))
                    break
                default:
                    return response.status = HttpServletResponse.SC_METHOD_NOT_ALLOWED
                    break
            }
        }catch(Exception ex){
            response.status = HttpServletResponse.SC_INTERNAL_SERVER_ERROR
            return  serializeData([message : ex.getMessage()], request.getHeader("Accept"))
        }
    }

    def paristatistic(){
        try {
            switch (request.getMethod()) {
                case "GET":
                    def pari = pariCustomService.mostBet()
                    println(pari + "*************")
                    def most = []
                    pari.each {
                        item ->
                            def count = item[0]
                            def team = item[1]
                            most.add([count: count, team: team])
                    }
                    serializeData(most, request.getHeader("Accept"))
                    break
                default:
                    return response.status = HttpServletResponse.SC_METHOD_NOT_ALLOWED
                    break
            }
        }catch(Exception ex){
            response.status = HttpServletResponse.SC_INTERNAL_SERVER_ERROR
            return  serializeData([message : ex.getMessage()], request.getHeader("Accept"))
        }
    }

    // à retester
    def changeDetailPariFinishedAndInsertMvnt(){
        try {
            switch (request.getMethod()){
                case "PUT":
                    def jsonObject = request.JSON
                    long idmatch = jsonObject.idmatch.toLong()
                    long idteamwinner = jsonObject.idteamwinner.toLong()
                    pariCustomService.udpateStatusIsFinishedByIdMatch(idmatch)
                    pariCustomService.findAllPariDetailByIdmatch(idmatch).each {
                        item ->
                            MvntAfterMatch mvntAfterMatch = new MvntAfterMatch()
                            if(item.idTeamParie == idteamwinner){
                                long millis=System.currentTimeMillis();
                                mvntAfterMatch.dateMvnt = new Date(millis)
                                mvntAfterMatch.parisDetail = item
                                mvntAfterMatch.credit = item.amountWithQuote
                                mvntAfterMatchService.save(mvntAfterMatch)
                            }
                    }
                    return serializeData([message : "Mise du statut détail pari est succès!"], request.getHeader("Accept"))
                    break
                default:
                    return response.status = HttpServletResponse.SC_METHOD_NOT_ALLOWED
                    break
            }
        }catch(Exception ex){
            response.status = HttpServletResponse.SC_INTERNAL_SERVER_ERROR
            return  serializeData([message : ex.getMessage()], request.getHeader("Accept"))
        }
    }
    def countParisWithParameterFinished(){
        try {
            switch (request.getMethod()) {
                case "POST":
                    def jsonObject = request.JSON
                    boolean isFinished = Boolean.valueOf(jsonObject.isFinished)
                    long max = jsonObject.max.toLong()
                    long offset = jsonObject.offset.toLong()
                    def paris = pariCustomService.countPariisFinished(isFinished, max, offset)
                    serializeData(paris, request.getHeader("Accept"))
                default:
                    return response.status = HttpServletResponse.SC_METHOD_NOT_ALLOWED
                    break
            }
        }catch(Exception ex){
            response.status = HttpServletResponse.SC_INTERNAL_SERVER_ERROR
            return  serializeData([message : ex.getMessage()], request.getHeader("Accept"))
        }

    }
}

backend-grails-pari/grails-app/controllers/backend/grails/pari/ApiTreasuryController.groovy
package backend.grails.pari

import grails.validation.ValidationException

import javax.servlet.http.HttpServletResponse
import java.sql.Date

class ApiTreasuryController extends ApiBasicController{
    MvntAfterMatchService mvntAfterMatchService
    PaymentService paymentService
    ParisDetailService parisDetailService
    MvntCustomService mvntCustomService

    def mvntAfterMatch(){
        try {
            switch (request.getMethod()){
                case "POST":
                    def jsonObject = request.JSON
                    MvntAfterMatch mvntAfterMatch = new MvntAfterMatch()
                    long millis = System.currentTimeMillis();
                    mvntAfterMatch.dateMvnt = new Date(millis)
                    mvntAfterMatch.debit = Double.valueOf(jsonObject.debit)
                    mvntAfterMatch.credit = Double.valueOf(jsonObject.credit)
                    def payment = paymentService.get(jsonObject.idpayment)
                    mvntAfterMatch.payment = payment
                    if(jsonObject.idparisdetail != null) {
                        def parisDetail = parisDetailService.get(jsonObject.idparisdetail.toLong())
                        mvntAfterMatch.parisDetail = parisDetail
                    }else
                        mvntAfterMatch.parisDetail = null
                    if (!mvntAfterMatch.validate()) {
                        throw new ValidationException('A movement after match validation error has occurred',mvntAfterMatch.errors)
                    }
                    def result = mvntAfterMatchService.save(mvntAfterMatch)
                    serializeData(result, request.getHeader("Accept"))
                    break
                default:
                    return response.status = HttpServletResponse.SC_METHOD_NOT_ALLOWED
                break
            }
        }catch (ValidationException validationException){
            response.status = HttpServletResponse.SC_BAD_REQUEST
            serializeData(validationException.errors, request.getHeader("Accept"))
        }
        catch(Exception ex){
            response.status = HttpServletResponse.SC_INTERNAL_SERVER_ERROR
            return  serializeData([message : ex.getMessage()], request.getHeader("Accept"))
        }
    }

    def solde(){
        try {
            switch (request.getMethod()){
                case "GET":
                    def result = mvntCustomService.calculateSolde()
                    serializeData([debit: result[0][0], credit:result[0][1], solde:result[0][2]], request.getHeader("Accept"))
                    break
                default:
                    return response.status = HttpServletResponse.SC_METHOD_NOT_ALLOWED
                    break
            }
        }catch (ValidationException validationException){
            response.status = HttpServletResponse.SC_BAD_REQUEST
            serializeData(validationException.errors, request.getHeader("Accept"))
        }
        catch(Exception ex){
            response.status = HttpServletResponse.SC_INTERNAL_SERVER_ERROR
            return  serializeData([message : ex.getMessage()], request.getHeader("Accept"))
        }
    }
}

backend-grails-pari/grails-app/controllers/backend/grails/pari/UrlMappings.groovy
package backend.grails.pari

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }
        "/api/payments" (controller: 'ApiPayment', action: 'payments')
        "/api/payments/historic" (controller: 'ApiPayment', action: 'paymentsHistoricByUser')
        "/api/top/user/investment" (controller: 'ApiPayment', action: 'topUserWithMiseMax')
        "/api/movement/after/match" (controller: 'ApiTreasury', action: 'mvntAfterMatch')
        "/api/solde/site" (controller: 'ApiTreasury', action: 'solde')

        "/api/paris" (controller: 'ApiPari', action: 'paris')
        "/api/pari" (controller: 'ApiPari', action: 'pari')
        "/api/pari/custom" (controller: 'ApiPari', action: 'paricustom')
        "/api/pari/details" (controller: 'ApiPari', action: 'pariwithdetails')
        "/api/pari/statistic" (controller: 'ApiPari', action: 'paristatistic')
        "/api/pari/movement" (controller: 'ApiPari', action: 'changeDetailPariFinishedAndInsertMvnt')
        "/api/pari/finished/count" (controller: 'ApiPari', action: 'countParisWithParameterFinished')

        "/api/match/mostbet" (controller: 'ApiMatch', action: 'matchPlusParie')


        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

backend-grails-pari/grails-app/views/paris/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'paris.label', default: 'Paris')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-paris" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-paris" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.paris}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.paris}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.paris}" method="POST">
                <fieldset class="form">
                    <f:all bean="paris"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

backend-grails-pari/grails-app/views/paris/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'paris.label', default: 'Paris')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-paris" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-paris" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.paris}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.paris}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.paris}" method="PUT">
                <g:hiddenField name="version" value="${this.paris?.version}" />
                <fieldset class="form">
                    <f:all bean="paris"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

backend-grails-pari/grails-app/views/paris/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'paris.label', default: 'Paris')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-paris" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-paris" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${parisList}" />

            <div class="pagination">
                <g:paginate total="${parisCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

backend-grails-pari/grails-app/views/paris/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'paris.label', default: 'Paris')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-paris" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-paris" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="paris" />
            <g:form resource="${this.paris}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.paris}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>